name: hello-production
version: "0.0.0"

dependencies:
- base >=4.9.1.0 && <5
- yesod >=1.6 && <1.7
- yesod-core >=1.6 && <1.7
- yesod-static >=1.6 && <1.7
- classy-prelude >=1.5 && <1.6
- classy-prelude-yesod >=1.5 && <1.6
- template-haskell
- wai-extra >=3.0 && <3.1
- yaml >=0.11 && <0.12
- http-client-tls >=0.3 && <0.4
- warp >=3.0 && <3.4
- aeson >=1.4 && <1.5
- monad-logger >=0.3 && <0.4
- fast-logger >=2.2 && <3.1
- wai-logger >=2.2 && <2.4
- file-embed
- wai
- foreign-store
- text
- containers
- hello-api

library:
  source-dirs: src
  ghc-options: -Wall

executables:
  hello-production:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hello-production

